import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import VoiceAssistantProvider from './context/VoiceAssistantProvider';
import DigitalHumanContainer from './components/DigitalHumanContainer/DigitalHumanContainer.component';
import ConversationContainer from "./components/ConversationContainer/ConversationContainer.component"
import HeaderContainer from './components/HeaderContainer/HeaderContainer.component'

export default function Home() {
  return (
    <>
      <Head>
        <title>AI Voice Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VoiceAssistantProvider>
        <HeaderContainer/>
        <main className={styles.main}>
          <DigitalHumanContainer/>
          <ConversationContainer />
        </main>
        </VoiceAssistantProvider>
    </>
  );
}